### ISSUE TITLE
honeypot-captcha Version

### ISSUE THREAD

**Issue by iloveitaly** [spree-contrib/spree_email_to_friend#20]
I've created a version of this extension which uses the [honeypot-captcha](https://github.com/curtis/honeypot-captcha) gem, which for some sites is a great alternative to ugly captchas.

I'd love to see the [honeypot-captcha branch](https://github.com/curtis/honeypot-captcha) of this extension exist as a branch on the main repository for others who might want to similar functionality.

**Comment by futhr** [comment]
PR still open https://github.com/sunlightlabs/rack-honeypot/pull/10

**Comment by joneslee85** [comment]
Too old. I am closing this issue for now.
